from pathlib import Path

from claude_agent_sdk import TextBlock

from src.agents.base import print_agent_message, run_agent_query

SYSTEM_PROMPT = """
You are an expert Software Engineer who writes clear, concise commit messages and PR bodies.

OUTPUT FORMAT (strict):
<commit_message>
[commit message here]
</commit_message>

<pr_body>
[PR body here]
</pr_body>

Do NOT include explanations, markdown code blocks, or conversational text outside these tags.

---

COMMIT MESSAGE RULES (Conventional Commits):

Format: <type>(<scope>): <subject>

Types:
- feat: New feature for the user
- fix: Bug fix for the user
- refactor: Code change that neither fixes a bug nor adds a feature
- perf: Performance improvement
- test: Adding/updating tests
- docs: Documentation only
- style: Formatting, semicolons, etc (no code change)
- chore: Build process, dependencies, tooling
- ci: CI/CD configuration
- revert: Reverting a previous commit

Scope: Derive from the primary directory or module changed (e.g., auth, api, ui, db).
If changes span multiple areas, use the most significant one or omit scope.

Subject: Imperative mood, < 50 chars, no period. ("add" not "added")

Body (include if changes span 3+ files or need explanation):
- Blank line after subject
- Bullet points for multiple changes
- Wrap at 72 chars

Footer: Reference ticket/issue numbers if known (e.g., "Refs: SCRUM-123")

EXAMPLES:

Good:
```
feat(auth): add Google OAuth login

- Add OAuth2 client configuration
- Create callback handler for token exchange
- Store refresh tokens in secure session

Refs: SCRUM-456
```

```
fix(api): handle null response from payment gateway
```

Bad:
- "Fixed stuff" (vague, past tense)
- "WIP" (not descriptive)
- "Update files" (doesn't explain what/why)

---

PR BODY RULES:

1. Start with 1-2 sentence summary of what this PR accomplishes
2. Include "## Changes" section with bullet points
3. Include "## Testing" section if changes need manual verification
4. Reference Jira ticket with link if known (e.g., "[SCRUM-123](https://jira.example.com/browse/SCRUM-123)")
5. Do NOT add "Generated by" or AI attribution footers

---

CONTEXT USAGE:
- Analyze `git diff --cached` to see actual code changes
- Use conversation history to understand the goal
- Ensure message accurately reflects what changed, not just the ticket description
"""

PROMPT = """
Generate a commit message and PR body for the staged changes.

Steps:
1. Run `git diff --cached` to see what's staged
2. Review conversation context for the goal
3. Write commit message and PR body based on actual changes

Output in the exact format specified in your instructions.
"""


async def generate_commit_and_pr_body(
    session_id: str, workspace_path: Path, mcp_config_path: Path | None = None
) -> tuple[str, str]:
    """
    Generate commit message and PR body based on session context and staged changes.

    Args:
        session_id: The session ID of the conversation to resume
        workspace_path: Path to the workspace root
        mcp_config_path: Optional path to mcp.json configuration file

    Returns:
        A tuple of (commit_message, pr_body)
    """
    full_response = ""
    async for message in run_agent_query(
        prompt=PROMPT,
        system_prompt=SYSTEM_PROMPT,
        allowed_tools=["Glob", "Bash", "Read", "Grep"],
        cwd=workspace_path,
        mcp_config_path=mcp_config_path,
        session_id=session_id,
    ):
        print_agent_message(message)
        if hasattr(message, "content"):
            for block in message.content:
                if isinstance(block, TextBlock):
                    full_response += block.text

    # Parse the response to extract commit message and PR body
    commit_message = ""
    pr_body = ""

    # Extract content between tags
    if "<commit_message>" in full_response and "</commit_message>" in full_response:
        start = full_response.find("<commit_message>") + len("<commit_message>")
        end = full_response.find("</commit_message>")
        commit_message = full_response[start:end].strip()

    if "<pr_body>" in full_response and "</pr_body>" in full_response:
        start = full_response.find("<pr_body>") + len("<pr_body>")
        end = full_response.find("</pr_body>")
        pr_body = full_response[start:end].strip()

    return commit_message, pr_body
